### ISSUE TITLE
fail to import clr

### ISSUE THREAD

**Issue by Enigma-song** [DaveSkender/Stock.Indicators.Python#298]
my python version is Python 3.10.4
I installed .net6.0 and stock-indicator, but when running 'import from stock_indicators import indicators', still showed the below error messages:

ImportError: fail to import clr.
Stock Indicators for Python has dependency on pythonnet, which uses CLR.
Check that you have CLR installed. It's currently using .NET6.
.NET:
	https://dotnet.microsoft.com/en-us/download/dotnet

**Comment by DaveSkender** [comment]
@LeeDongGeon1996 does this require a one-time `pip install -r requirements.txt` command to get all the prerequisites installed?

**Comment by LeeDongGeon1996** [comment]
Hi, @Enigma-song .
Can I know which version of clr-loader you are using? You can check with `pip list | grep clr-loader`.
There was a bug in clr-loader finding dotnet root and fixed in its latest version. If you are not using the latest, please upgrade clr-loader and try again.


@DaveSkender No, that file is just for developing. And will be excluded in deploy package.

**Comment by Enigma-song** [comment]
> 
Name: clr-loader
Version: 0.2.5

**Comment by LeeDongGeon1996** [comment]
@Enigma-song Sorry for late reply. Can you share the error message when you purely import `clr` only?  It is more likely to get the answer from pythonnet repository.
