### ISSUE TITLE
ZigZag indicator possible look ahed bias error

### ISSUE THREAD

**Issue by luigif2000** [DaveSkender/Stock.Indicators.Python#363]
Dear,
my relative ZigZag feauters created as foolow:

def calculate_zigzag_features(df):
    # Converti il DataFrame in una lista di istanze Quote utilizzando l'indice datetime
    quotes_list = [
        Quote(d, o, h, l, c, v)
        for d, o, h, l, c, v
        in zip(df.index, df['open'], df['high'], df['low'], df['close'], df['volume'])
    ]

    # Calcola l'indicatore ZigZag per ogni finestra di interesse e aggiungi le relative features al DataFrame
    for window in [3,5, 10]:
        # Calcola l'indicatore ZigZag
        zigzag = indicators.get_zig_zag(quotes_list, EndType.CLOSE, window)

        # Crea un DataFrame a partire dai risultati dell'indicatore Zig Zag
        zigzag_df = pd.DataFrame([(z.date, z.zig_zag) for z in zigzag], columns=['Date', f'ZigZagValue_{window}'])
        zigzag_df['Date'] = pd.to_datetime(zigzag_df['Date'])
        zigzag_df.set_index('Date', inplace=True)

        # Unisci i DataFrames
        df = df.join(zigzag_df, how='left')

        # Assicurati che i valori ZigZag siano in formato float
        df[f'ZigZagValue_{window}'] = df[f'ZigZagValue_{window}'].apply(lambda x: float(x) if x is not None else None)

        # Calcola la direzione del Zig Zag e convertila in valori interi
        direction_map = {'Up': 1, 'Down': -1, 'Flat': 0}
        df[f'ZigZagDirection_{window}'] = df[f'ZigZagValue_{window}'].fillna(0).diff().apply(lambda x: 'Up' if x > 0 else ('Down' if x < 0 else 'Flat')).map(direction_map)

        # Calcola l'indicatore Zig Zag relativo
        df[f'ZigZagRelative_{window}'] = ((df[f'ZigZagValue_{window}'].fillna(0) - df['close']) / df['close']) * 100

    return df

return a very high importance from my classificator model searcher!

Could be a look ahed bias problem in the indicator!?!?

Thanks in advance and waiting Your kindly reply.

luigi

**Comment by DaveSkender** [comment]
There's certainly a known amount of historical value [repainting](https://www.google.com/search?q=stock+indicator+repainting) with the [Zig Zag](https://python.stockindicators.dev/indicators/ZigZag/#content) indicator.  I suspect my term "_repainting_" is mostly the same idea as a [look-ahead bias](https://www.investopedia.com/terms/l/lookaheadbias.asp).  This happens in several indicators in the library.  It's not a bug, it's just how the indicator was written by the original author -- I don't invent these things.

To help users identify indicators that repaint (or have convergence related initialization errors), we've put these warnings in our documentation, like this one for [Zig Zag](https://python.stockindicators.dev/indicators/ZigZag/#returns):

<img width="620" alt="image" src="https://github.com/DaveSkender/Stock.Indicators.Python/assets/8432125/fd2b81d8-5b0e-4250-a571-d95bbe97ff4c">

**Comment by DaveSkender** [comment]
I’d call this one more of a _price overlay_ than an actual indicator of future performance.

**Comment by luigif2000** [comment]
Dear Dave, thanks a lot for reply, that's very kind of You.
Yes repaint=lookahed bias; it's not good proprieties of financial indicator.....when used in machine learning prediction model discover it's a big problem; must avoid.

I will study more about; it's no easy.

Please let us know, when you have time, no urgent, how to collect Your most important indicators, NO repaint, in order to use to create features <- this is the most important use in AI era.

thanks in any case, sorry for my bad english and wish You the best!.

luigi

**Comment by DaveSkender** [comment]
I don't have a pre-determined list of _the most important indicators_ since I've not done a full analysis of all possibilities.  Some of my personal favorites recently are ATR Trailing Stop, Elder Ray Index, Schaff Trend Cycle.  I'd started a discussion on the topic:

- https://github.com/DaveSkender/Stock.Indicators/discussions/708

My personal philosophy to developing a trading strategy is much more broad than just finding that one perfect indicator, but rather it follows this this logic:

1. **Do not rely on one indicator** for a trade signal.  Consider that you may have one triggering signal event, but that it is also confirmed with one or more other indicators that depict favorable conditions.
2. **Use backtesting** on multiple securities to confirm your hypothesis, but understand that changing market conditions may make backtesting an invalid test of your strategy looking forward.  Be careful of curve-fitting and reverse-engineering where your strategy works perfectly for a single security, but fails everywhere else.
3. The industry standard settings for indicators **may not be the best settings** and that many or most indicators are terrible.  Don't believe everything you read in blogs and be cautious around charting sites that share unverified user-defined indicators.
4. **Strategies often do not transfer across asset classes**.  For example, a strategy that works with equities might not work with currencies.
5. **Finding your own strategy is a journey** of personal preferences, homework, testing, and continuous improvement.

It should be noted, that my approach to developing a strategy is constantly evolving and is still a work in progress and probably will be for a very long time.

_Originally posted by @DaveSkender in https://github.com/DaveSkender/Stock.Indicators/discussions/277#discussioncomment-287215_

**Comment by luigif2000** [comment]
Thanks a lot Dear Dave,
You are a good guy.....i wish you the very best.

Luigi

Il Gio 4 Apr 2024, 16:36 Dave Skender ***@***.***> ha scritto:
