### ISSUE TITLE
`IEnumerable` won't be auto-converted in pythonnet 3.0.0

### ISSUE THREAD

**Issue by LeeDongGeon1996** [DaveSkender/Stock.Indicators.Python#58]
## The problem

Pythonnet will not convert `IEnumerable` of C# to `list` of Python anymore from the version 3.0.0.
Our `_verify_data()` method checks the data is subclass of `list` or not and so it'll never be passed.
That means testcases will be failed if we use pythonnet 3.0.0.

https://github.com/DaveSkender/Stock.Indicators.Python/blob/36c45c5d118d360e4a40650996cee1690fe329f0/stock_indicators/indicators/common/results.py#L57

##  Related Issue
 - https://github.com/pythonnet/pythonnet/issues/1622

**Comment by LeeDongGeon1996** [comment]
I will fix it after bumping up pythonnet version.

**Comment by LeeDongGeon1996** [comment]
@DaveSkender While testing to bump up pythonnet, I've figured out that pythonnet v3.0.0-alpha is 2~3x slower than v2.5.2 we are currently using. Actually this problem is out of our control, but now, I'm just curious about specific level of performance for product(release) version. I don't have any idea how much of performance achievement can be accepted for end-users. I think you might have some idea of this, can you let me know about it?

**Comment by DaveSkender** [comment]
My general thought is complex on this issue:

1. It's probably okay for casual users; but, will be a problem for high-frequency or large data users.
2. It's probably okay to do an initial release v0.1.0 and continue to work on it; hopefully with more community feedback
3. There are probably some things I can do in the core DLL to improve its performance on some of the slower indicators, so that can help a bit in some areas
4. We'll continue to do research and experimentation to make it faster, as is
5. We can plan to slowly replace wrapper code with native Python indicator calculations over time

**Comment by LeeDongGeon1996** [comment]
Thank you for your answer. 5 would be one of the good way we should go. I thought we are close to `done`, but now it sounds like we've just started, haha
