### ISSUE TITLE
Refactor test data

### ISSUE THREAD

**Issue by LeeDongGeon1996** [DaveSkender/Stock.Indicators.Python#78]
It seems like the test data including whole period of results for each indicator is ready to be used. If it is correct, I'm planning to write unit tests using xlsx files in each indicator directory. Is it available now?

 - https://github.com/DaveSkender/Stock.Indicators/pull/553

**Comment by LeeDongGeon1996** [comment]
Can I know the reason why you are not using them?

**Comment by DaveSkender** [comment]
> Can I know the reason why you are not using them?

1. I tend to clean up the Excel files for formatting so they tend to not have a stable layout that might break the test data importer.  Since I tend to do TDD, it's not unusual for me to come back and revise the reconcile calculations throughout the development process.
2. I do actually review the full results and compare them.  In the spreadsheets, you'll see manual calcs (blue table) and indicator output (yellow); so essentially I am already doing a full compare.
2. It makes the whole test much slower overall to import results.  CSV import is much faster than Excel and JSON; however, CSV is still a lot slower than sampling.  Sampling is still a statistically acceptable approach.
3. I'm lazy and it's a low ROI effort.  There are several alternate test scenarios for each indicator and it could be a lot of work to switch them over, with only a little added benefit.  It would have been much easier to start with that approach.

**Comment by LeeDongGeon1996** [comment]
Your words make sense. I thought using spreadsheet having whole period of results can make writing unittest faster, without losing its original goal.
Anyway, I'll put off switching it.
